### ISSUE TITLE
plugin 1.2.5 : is possible to add some type of line for create indent + 1 

### ISSUE THREAD

**Issue by marteloudini** [camel-tooling/camel-idea-plugin#1000]
Hello Mr Ibens,

when i do pretty format (ALT+CTRL+L) , i have only FROM line is indent (with nice icone camel :-) )
but is very great if all other can do that 
**(example ident + 1 )**
.when
.otherwise
.filter
.try
**(example ident -1 )**
.end
.endChoice

is possible ? 

thanks

**Comment by essobedo** [comment]
It is not clear to me, could you please provide an example of a route that is not formatted properly?

**Comment by davsclaus** [comment]
user did not respond closing
