### ISSUE TITLE
Plugin not working on Intellij 2024.2

### ISSUE THREAD

**Issue by eduardozecca** [camel-tooling/camel-idea-plugin#1039]
My IntelliJ community edition just updated to the version 2024.2  (Builtld #IC-242.20224.300, built on August 6, 2024). I had the version 0.5.5 of the plugin installed and working but now it does not work and when I try to install the version 1.2.10 it says that is not compatible.

**Comment by davsclaus** [comment]
There last version today is 2024.1.6 and this version is supported by latest plugin release.

Are you using some Early Access version?



IntelliJ IDEA 2024.1.6 (Community Edition)
Build #IC-241.19072.14, built on August 8, 2024
Runtime version: 17.0.11+1-b1207.30 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.6.7
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.images.show.chessboard=true
Non-Bundled Plugins:
  com.intellij.ideolog (222.3.2.0)
  DevKit (241.19072.18)
  Docker (241.19072.14)
  org.asciidoctor.intellij.asciidoc (0.42.2)
  org.apache.camel (1.2.10)
Kotlin: 241.19072.14-IJ

**Comment by davsclaus** [comment]
Ah okay I had to update first to latest 2024.1.x before they would let me upgrade to 2024.2.x

**Comment by darkblackside** [comment]
I've the same problem. Curious why I was using 0.5.5 before for some months. Looks like there was a higher version all the time.

**Comment by mucek4** [comment]
I am not sure it's solved: I have IntelliJ IDEA 2024.2.2 (Ultimate Edition) Build #IU-242.22855.74, built on September 18, 2024 and the latest version of plugin is 0.5.5. Why the latest plugin is 6 years old?

**Comment by davsclaus** [comment]
there is no new release yet ... say wait

**Comment by mucek4** [comment]
@davsclaus but shurely there is a newer version than 0.5.5. Cause the 0.5.5 version just doen not work.

**Comment by davsclaus** [comment]
yes but its IDEA that has some version ranges of compatability and then it just shows a version old version before they introduced that
