### ISSUE TITLE
Plugin 'Apache Camel' (version '1.2.10') is not compatible with the current version of the IDE because it requires build 241.*

### ISSUE THREAD

**Issue by zigac9** [camel-tooling/camel-idea-plugin#1049]
Plugin 'Apache Camel' (version '1.2.10') is not compatible with the current version of the IDE, because it requires build 241.* or older but the current build is IU-242.21829.142

**Comment by essobedo** [comment]
Thx for reporting, it is a known issue https://github.com/camel-tooling/camel-idea-plugin/issues/1039
