### ISSUE TITLE
Language Server Protocol

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#15]
Wonder if IDEA supports LSP or we can have some reuse of the plugin so parts of it can be used in Eclipse / Eclipse Che or other editors which can support LSP as well.

There are surely parts of this plugin that touches the camel catalog and checks the endpoint uri etc, that can be made reusable without relying on IDEA APIs.

**Comment by davsclaus** [comment]
See more details at
https://github.com/Microsoft/language-server-protocol/wiki/Protocol-Implementations

**Comment by davsclaus** [comment]
There is some work about this at
https://github.com/lhein/camel-language-server

**Comment by davsclaus** [comment]
The eclipse users and web editors are asking about LSP so it may be worthwhile to make this plugin code reusable outside IDEA, eg the logic that does the auto completion and list which options you can choose etc.

**Comment by apupier** [comment]
LSP is now available in IntelliJ through this plugin: https://plugins.jetbrains.com/plugin/10209-lsp-support

I created https://github.com/lhein/camel-language-server/issues/62 

being able to share the code is more and more relevant :-)

**Comment by davsclaus** [comment]
We are getting closer to having a mutual interest of have some shared code for IDEA and Eclipse in this git organization so Camel tooling on both editors can be awesome. With LSP then Eclipse can do the code assistance we are doing already in IDEA. And eventually if LSP becomes included OOTB in IDEA we can have more shared code.

But at first we can potentially have a git organization that can include both and have repos for
- common
- idea
- eclipse

It would take time to find the common code and have that refactored out to an individual common component. So for starters this may be

- camel-idea-plugin
- camel-tooling-lsp

And then over time we have some common code in a common/core tooling module

- camel-idea-plugin
- camel-tooling-lsp
- camel-tooling-core

**Comment by lhein** [comment]
Claus, the idea of LSP is to separate out the logic for code completion, hovers, documentation etc into a shared server "application". Whatever clients you then use you can (if this client supports LSP) have a client plugin which talks with the LSP server and provides all the functionality the server has to offer.

So from a logical point of view we should split the repositories in "server" and "clients". As a first goal it would definitely make sense to extract common / shared code into a common repo with the goal to make it easier later on to merge that code into the LSP server or to provide a library which then is used by the LSP server.

For the client side we already prepared basic clients for Visual Studio Code, Eclipse and Eclipse Che (see https://github.com/lhein/camel-language-server/tree/master/clients) The LSP server we currently have is limited to XML DSL but it would be really awesome to make it work for Java at least too.

**Comment by davsclaus** [comment]
Created a ticket about organization renaming #408

**Comment by apupier** [comment]
the Camel LSP has been moved under the same organization: https://github.com/camel-tooling/camel-language-server

**Comment by davsclaus** [comment]
IDEA dont support LSP so lets close this for now

**Comment by apupier** [comment]
> IDEA dont support LSP so lets close this for now

there is a community extension for that https://github.com/gtache/intellij-lsp

But current Camel IntelliJ plugin is benefiting from the IntelliJ API to provide different features. As long as there are people to maintain it, no real advantage to use Camel LSP.

**Comment by fharms** [comment]
People maintaining the plugin for now is very limited and spontaneously, so I will have no objections against using the Camel LSP instead, if that give us an advantage to share features across platforms and more ppl to help maintaining the plugin.

I don't have any knowledge regarding LSP, so a few questions / concerns, do we have the same feature set available in the LSP as we have in the Intellij API? 

It seems to me the Intellij LSP plug-in is more and less maintained by one person, this is pretty much the same for the Camel Intellij plugin at the moment. 

If we switch to LSP this will mean we also need to help maintaining the Intellij LSP project, and the few ppl maintaining the Camel Intellij plugin today, I'm not sure it will be an advantage for us.

**Comment by apupier** [comment]
> do we have the same feature set available in the LSP as we have in the Intellij API?

no. LSP is a providing a subset of IntelliJ API.

The main differences currently between Camel LSP and Camel IntelliJ I'm aware of are:
- completion in IntelliJ for components is based on available dependencies in pom.xml (which means needs to add depepencies first in pom.xml) although with LSP we are providing all components from the catalog
- Camel IntelliJ has (which Camel LSP doesn't have):
  - Code completion for Camel property placeholders https://github.com/camel-tooling/camel-language-server/issues/29
  - external link to Camel component documentation opening in web browser
  - Supports 3rd party Camel components https://github.com/camel-tooling/camel-language-server/issues/45
  - Camel icon in gutter (not part of LSP)
  - Attempts to use same version as camel-core dependency from the loaded project https://github.com/camel-tooling/camel-language-server/issues/38
  - Supports loading camel-catalog from third party Maven repositories define in the project Maven pom.xml file
- Camel LSP has (which Camel IntelliJ doesn't have):
  - Support for Camel-K Groovy (and soon Kotlin and JS) files
  - Support for Camel Kafka Connect properties file
  - Reused code in Eclipse Desktop, VS Code, Eclipse Che and Atom. It is reusable by configuration in IntelliJ and Sublime (and in theory in Emacs and vim and some others editors)
  - outline
  - Auto-completion for referenced IDs of direct, direct VM, VM and SEDA components (XML DSL only) (i thought IntelliJ has it but cannot find it in doc today)
  - Specific documentation on hover on attributes (not the whole doc of the component)

In a general way, developing for a specific IDE is more powerful than using LSP when looking at this IDE only. The IDE apis are providing a lot of good tools. For LSP, it would mean being able to reuse other LSP. It is currently quite complicated, even if not impossible. For instance, SpringBoot is providing a LSP reusing XML LSP and Java LSP.

> It seems to me the Intellij LSP plug-in is more and less maintained by one person, this is pretty much the same for the Camel Intellij plugin at the moment.
> 
> If we switch to LSP this will mean we also need to help maintaining the Intellij LSP project, and the few ppl maintaining the Camel Intellij plugin today, I'm not sure it will be an advantage for us.

good point, IntelliJ has a small contributor community compared to most of the other IDEs and seems Jetbrains doesn't want to embrace the LSP themselves (I think they see it as endangering their business model but this is my personal point of view :-)).
For IntelliJ LSP, we can expect more chance to have help from community than for only Camel IntelliJ but it stays a bet.
