### ISSUE TITLE
Find Usages Provider - Camel Routes

### ISSUE THREAD

**Issue by fharms** [camel-tooling/camel-idea-plugin#23]
If you are inside a route and need the from/to Usages. Same functionality you can do with Java

for example if you find usages from "timer:trigger" it should list the "timer:status"
```java
from("timer:trigger")
    .transform().simple("ref:myBean")
    .to("log:out");

from("timer:status")
    .bean(health, "invoke")
    .log("Health is ${body}");
```

**Comment by davsclaus** [comment]
Yeah we have a bit related to this with the clicking on the camel icon in the gutter to show list of which other routes is calling me.

**Comment by davsclaus** [comment]
There is a com.intellij.lang.findUsages.FindUsagesProvider however it may seem you cannot have that as fallback so the regular java / xml find usages runs first and calls ours in case they cannot do it.

**Comment by fharms** [comment]
Close this because it's implemented with the latest improvement to lookup direct routes
