### ISSUE TITLE
Error reporting feature

### ISSUE THREAD

**Issue by adrianbumbas** [camel-tooling/camel-idea-plugin#248]
Since users are starting to report crashes on this plugin we can use the IntelliJ platform's features to do that, even reporting directly to GitHub like this one from the Go lang plugin https://github.com/go-lang-plugin-org/go-lang-idea-plugin/pull/909

**Comment by bennetelli** [comment]
@davsclaus @fharms we need to authenticate to report plugin errors as GitHub issues.

The Go plugin first started with a OAUTH token authentication and replaced it with an App Engine Proxy later.
Someone of you have experiences with it? What's the best way to do it?
PS: It's not possible to file issues via GitHub API without an authentication. 

One way could be storing a generated OAUTH token in the plugin. What do you think of it? 
Maybe this could lead to lots of issues reported by a "dummy-user" and not the reported user itself?

**Comment by davsclaus** [comment]
Yeah frankly I dont really want such a feature - too much noise compared to too few of us, and we only work on this in our spare time. People can easily report issues in github already.

This kind of feature with auto reporting is more for enterprise products where you have a support team behind that is paid to support - not us that just want a bit of fun in our limited spare time

**Comment by fharms** [comment]
I agree with @davsclaus on this.

**Comment by bennetelli** [comment]
so I will try to implement it and if it doesn't work within some hours of work I will quit and the feature won't be implemented.

**Comment by bennetelli** [comment]
nevertheless I don't think there will be a flood of issues after adding this feature.

**Comment by fharms** [comment]
Close this since we haven't seen the need for an automatic error reporting feature.
