### ISSUE TITLE
Add support for completion list of Camel bean method names

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#318]
So if you have a 
```
<bean id="foo" method="<CURSOR>"/>
```
Then we can try to see if we can lookup the bean and its class, and see if IDEA has any knowledge of which methods the bean offers, so we can show in the list.

For example the Camelry plugin has that
https://github.com/AlanFoster/Camelry/blob/master/documentation/screenshots/IntelliSense.png

**Comment by fharms** [comment]
And it could be nice if we could jump from the CURSOR to the actually code

**Comment by fharms** [comment]
I guess the tricky part is when id="foo" is used as a bean reference you will have to locate source file declaring this specific bean, and the same goes for `bean(myObject, "<CURSOR>) `

For `bean(MyClass.class, "<CURSOR>) ` it's much simpler and I think I will start with this.

**Comment by fharms** [comment]
Bean reference as id. I guess you can travers the PSI tree for all `@component` annotations, but if it will be efficient is the question 

`
@Component("myBean")
public class MyBean {}

from(...)
  .to("bean:\<caret\>) 
`

**Comment by moelholm** [comment]
It would be awesome if the method list would show methods from the superclasses too. For example:

class GenericSuperClass<T>{
    abstract T doVaryingStuff();

    public T process() {
           T t = doVaryingStuff();
           // do stuff with t
           return enrich(t);
    }
}

class ActualBeanClass extends GenericSuperClass<String> {
    String doVaryingStuff() {
          return “dog”;
    }
}


If I use ActualBeanClass in my route.... then I would expect to find method “process” to invoke into the pop up list. Useful for template method stuff (https://en.m.wikipedia.org/wiki/Template_method_pattern).

**Comment by moelholm** [comment]
(... a variant of this could be java8 default methods from interfaces implemented by the bean.)

**Comment by fharms** [comment]
Thanks @moelholm and I just implemented for showing method for super classes also

**Comment by fharms** [comment]
@davsclaus @bennetelli Folks, I have been working on the bean smart completion and tried to unit test it, but IDEA test framework gives me a headache.

Take a look here https://github.com/fharms/camel-idea-plugin/tree/java_bean_method_completion the test case `JavaBeanSmartCompletionTestIT` it does not return any suggestions though the smart completion code is executed.  it's also working fine in the client too.

Any suggestions on how to test this?

**Comment by fharms** [comment]
First version with limit support for bean method completion #385

**Comment by fharms** [comment]
Closing this since the bean support has come a long way since this was create.
