### ISSUE TITLE
Migrate Build from Maven to Gradle

### ISSUE THREAD

**Issue by bennetelli** [camel-tooling/camel-idea-plugin#382]
migrate build scripts from Maven to Gradle. It will make it easier to update the plugin in case of a new IDEA version. It will also decrease the turnaround times when building and testing the plugin manually.

* first we have to migrate to Gradle
* then we have to add this plugin to the build.gradle file: https://github.com/JetBrains/gradle-intellij-plugin

**Comment by bennetelli** [comment]
current status: all projects are building with Gradle, but the camel-maven-plugin and some other maven plugins are not migrated yet. I will use Andrea's implementation of Camel-Gradle-Plugin if it works as expected.

**Comment by davsclaus** [comment]
@bennetelli ah that custom-components example stuff is for support for camel comnnectors. Its not so needed anymore so we could potentially remove those to make the gradle migration easier and faster.

**Comment by davsclaus** [comment]
The maven build is getting painful, we should migrate soon as upgrading to 2018.3.4 is a pain

**Comment by fharms** [comment]
fixed in #490
