### ISSUE TITLE
Rename organisation to camel-tooling

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#408]
So the organization can host tooling for other IDEs such as Eclipse, Che, and others. And also tooling that may not be tied to an IDE editor.

We can then have some more common modules that the different tools can reuse, as there is a bunch of logic in the existing camel-idea-plugin that is not directly coupled to the IDEA API but would benefit being neutral and reusable by other tools.

Currently how the camel-idea-plugin is built and released is that its just a .zip file that has everything that gets updated at a jetbrains website.

If we need to release JAR files to maven central, then we need to use maven coordinate that is not `org.apache` as they are the ASF organization. And therefore we need to use `org.cameltooling` or something like that. But that is a discussion to take when we get to that bridge.

Notice that its only the organization that will be renamed. Each sub-project in this organization will have its own git repo, eg the `camel-idea-plugin` git repo will stay as-is.

**Comment by lhein** [comment]
Sounds like a good starting point.

**Comment by lhein** [comment]
I started moving over the lsp codebase into this organization. For this I created 3 repos ... 1 server and 2 client repos.

**Comment by apupier** [comment]
> I started moving over the lsp codebase into this organization. For this I created 3 repos ... 1 server and 2 client repos.

I think it will be worthy to redo the move keeping the history, it contains useful information on why code is written in one way or another.

**Comment by lhein** [comment]
@davsclaus given that the new org name will be "camel-tooling" how about a slightly different org icon? maybe a camel with some tools? I will try an mess around later a bit for a prototype.

**Comment by davsclaus** [comment]
Yeah sure a new icon would be nice

**Comment by lhein** [comment]
@davsclaus Can I suggest a different GAV?
Given that we want to deploy some artifacts to central we will have issues with claiming groupId org.cameltooling as we don't own that domain, right?
So an easier approach would be to use com.github.cameltooling as groupId. That is a notation suggested by Sonatype.

Let me know what you think.

**Comment by lhein** [comment]
@davsclaus @fharms @bennetelli @apupier I'd like to push for the rename and I would also like to suggest that we define our new Maven GroupID. Any objections? Any suggestions for groupid? Please be aware that we need to own the domain for deploying to Central....means if we go for org.cameltooling then we should own www.cameltooling.org....otherwise it will be hard to claim ownership. Suggestion from sonatype docs.....use com.github.<org-name>.

**Comment by lhein** [comment]
![cameltoolinglogo](https://user-images.githubusercontent.com/435853/37769082-22be3250-2dd0-11e8-98f4-591b0aec4e44.png)

**Comment by davsclaus** [comment]
Yes we would need to use a Maven GAV we can use for release. So the `org.github...` is fine with me.

**Comment by davsclaus** [comment]
Okay I think we should rename this organization in the weekend - that gives a little time for @fharms and @bennetelli to catch up.

Here is what github says about a rename with what happens automatic and what not.
https://help.github.com/articles/renaming-an-organization/

So what if we do

1. Rename the organization to `camel-tooling` on saturday
2. Update the organization logo to the one that @lhein posted above
3. Refactor the source code to use `com.github.cameltooling` as base package name.

Any comments

**Comment by lhein** [comment]
I'd keep organization name equal to the package name and groupId

**Comment by davsclaus** [comment]
We have renamed now
