### ISSUE TITLE
Camel icon in rest-dsl do not show if you start with rest() and not rest("somename")

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#413]
I noticed that the icon is not shown if you just have

     rest()
       .get("/{id}")...

But if you have (its shown)

     rest("/")
       .get("/{id}")...

Or

     rest("/somename")
       .get("/{id}")...

**Comment by bennetelli** [comment]
@davsclaus of course :)

**Comment by essobedo** [comment]
The corresponding PR https://github.com/camel-tooling/camel-idea-plugin/pull/767
