### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#420]
From `org.apache.camel` to `com.github.cameltooling`

And our Maven GAV as well

groupId = `com.github.camel-tooling`    (notice it has a dash)

**Comment by fharms** [comment]
@davsclaus Is this really something we need to do?

**Comment by davsclaus** [comment]
Yeah ideally we should do this. But we dont do Maven releases so its not so problematic where this tool will mix up with regular Apache Camel.

**Comment by davsclaus** [comment]
@fharms with the change to gradle, then i think its a good idea to change the package name too at the same time, and when we do a new release we can bump the version number up

**Comment by fharms** [comment]
fixed in #490
