### ISSUE TITLE
IDEA 2018.1 ultimate does not work for plugin development

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#429]
After the 2018.1 upgrade we have errors with ultimate with all sorts of error :(

I dont have time for this shit!

**Comment by fharms** [comment]
Use the CE version 🙂

**Comment by davsclaus** [comment]
CE dont have spring boot support and there are a lot of ultimate users.

**Comment by fharms** [comment]
So are you saying the plugin is not working on ultimate when you install it?

**Comment by davsclaus** [comment]
Oh I havent tested that, but I will install a 2nd idea and have both CE and ultimate, and then have to use CE for plugin development. 

I would assume the plugin would work on ultimate, its likely only the plugin development that dont work.

Hopefully switching to gradle will make the build better and potentially get both of them working again.

**Comment by bennetelli** [comment]
@davsclaus what exactly is wrong with your environment? I just checked out the master and everything works fine in my console.

**Comment by davsclaus** [comment]
Okay lets just use the free version for plugin development
