### ISSUE TITLE
use model classes in camel-tooling-commons

### ISSUE THREAD

**Issue by lhein** [camel-tooling/camel-idea-plugin#430]
Aurelien extracted model classes from the idea plugin a while back and ported those to the camel-tooling-common module at https://github.com/camel-tooling/camel-tooling-common/tree/master/src/main/java/com/github/cameltooling/model

It would be nice if you could move your latest changes to those classes into the commons module and start to use it. Sharing our code between the different toolings would be really awesome.

**Comment by fharms** [comment]
Closing this since the `camel-tooling-common` is archived, and with the work in progress for supporting camel 3 we are using the model classes that comes with the `org.apache.camel:tooling` library
