### ISSUE TITLE
Apache ActiveMQ ConnectionFactory illegal option

### ISSUE THREAD

**Issue by FrederikBrinckTruelsen** [camel-tooling/camel-idea-plugin#435]
I have configured the connection factory and the plugin claims its an illegal option. The configuration of the endpoint looks like this.

activemq:Consumer.Baz.VirtualTopic.FooRequest?connectionFactory=#pooledJmsConnectionFactory"

Version: 0.5.2

**Comment by davsclaus** [comment]
Can you post the actual code you have around configuring the AMQ CF, so we can use this to reproduce the issue and work on a fix

**Comment by davsclaus** [comment]
@FrederikBrinckTruelsen did you get some time to build a small example or provide a bit more details?

**Comment by davsclaus** [comment]
Any update on this, and what version of Camel and ActiveMQ are you using?

**Comment by davsclaus** [comment]
We cannot reproduce this with latest Camel version.

**Comment by FrederikBrinckTruelsen** [comment]
Sorry for the delay and if you need more infomation ill try to be more available. I have the previous mentioned queue defined as a constant and its the error on the #pooledJmsConnectionFactory part of the constant. A colleague and I experience the same problem across projects where we use this queue configuration.

We use the following versions:
Apache Camel 2.19.1
JBoss A-MQ 6.2
Apache Camel Plugin: 0.5.2

**Comment by FrederikBrinckTruelsen** [comment]
@davsclaus 

I guess you did not see my previous message as you closed the issue
