### ISSUE TITLE
Upgrade to IntelliJ ideaIC-2018.3.2 showing large camel icon on gutter

### ISSUE THREAD

**Issue by shoaibjdev** [camel-tooling/camel-idea-plugin#465]
@davsclaus Right after upgrading the IntelliJ IDEA to **ideaIC-2018.3.2** on Mac all camel routes started displaying camel icon occupying 50% of the screen.

**Screenshot below:**
[https://ibb.co/wpzBgff](url)

<a href="https://ibb.co/wpzBgff"><img src="https://i.ibb.co/3SC4dnn/Screenshot-2019-01-03-at-11-14-15-AM.png" alt="Screenshot-2019-01-03-at-11-14-15-AM" border="0"></a><br /><a target='_blank' href='https://poetandpoem.com/analysis-of-the-rose-that-grew-from-concrete-by-tupac-shakur'>flower in concrete poem</a><br />

**Comment by davsclaus** [comment]
We cannot reproduce this with newer version of the plugin and IDEA.
