### ISSUE TITLE
Unclear implementation of XmlCamelIdeaUtils#isCamelRouteStart

### ISSUE THREAD

**Issue by rastislavpapp** [camel-tooling/camel-idea-plugin#475]
Hello,

I'm trying to extend some functionality in this plugin. I'm trying to reuse method XmlCamelIdeaUtils#isCamelRouteStart for my purposes, but I'm a bit uncertain about the implementation.

Specifically, this part:  
```
if (parentTag != null) {
    boolean xmlEndTag = element.getPrevSibling().getText().equals("</");
    return "routes".equals(parentTag.getLocalName()) && "rest".equals(name) && !xmlEndTag
        || "route".equals(parentTag.getLocalName()) && "from".equals(name);
}
```
This would mean that these two elements are considered to be starts of a route:
* ```<rest>```, if it's parent is ```<routes>```
* ```<from>```, if it's parent is ```<route>```

I've never encountered the ```<routes>``` tag, but according to blueprint xsd it can only have a ```<route>``` as it's child:
```
<xs:complexType name="routesDefinition">
    <xs:complexContent>
      <xs:extension base="tns:optionalIdentifiedDefinition">
        <xs:sequence>
          <xs:element maxOccurs="unbounded" minOccurs="0" ref="tns:route"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
```
Maybe it is supposed to be ```<rest>``` with ```<route>``` parent?

**Comment by davsclaus** [comment]
Yeah its not so commonly known, but you can load xml files into Camel for both routes and rests via a xml file
```
<rests xmlns="http://camel.apache.org/schema/spring"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <rest path="/users">
    <get uri="/view/{id}">
      <to uri="direct:getUser"/>
    </get>
  </rest>

</rests>
```

**Comment by davsclaus** [comment]
And for routes
```
<routes xmlns="http://camel.apache.org/schema/spring">
    <route id="foo">
        <from uri="direct:start"/>
        <choice>
            <when>
                <xpath>/a/foo = 'bar'</xpath>
                <to uri="mock:bar"/>
            </when>
        </choice>
    </route>
</routes>
```

**Comment by davsclaus** [comment]
And a more normal rest in XML would be
```
  <camelContext xmlns="http://camel.apache.org/schema/spring">

    <rest>
      <get uri="/ping">
        <route>
          <setBody>
            <constant>pong</constant>
          </setBody>
        </route>
      </get>
    </rest>

  </camelContext>
```

**Comment by davsclaus** [comment]
So the code should likely be

     return "camelContext".equals(parentTag.getLocalName()) && "rest".equals(name) && !xmlEndTag

**Comment by fharms** [comment]
@rastislavpapp is this still an issue?

**Comment by rastislavpapp** [comment]
It is ok now, I'm closing the ticket.
