### ISSUE TITLE
Plugin complains that VM scheme accepts "concurrentConsumers" options only for producer 

### ISSUE THREAD

**Issue by fg78nc** [camel-tooling/camel-idea-plugin#477]
Plugin complains that VM scheme accepts "concurrentConsumers" options only for producer, while it is applicable for both producer and consumer (to correctly identify queue) 

![image](https://user-images.githubusercontent.com/18621236/54872828-f7434d80-4da0-11e9-8e8f-f7394fcbf036.png)

**Comment by davsclaus** [comment]
What version of Camel are you using?

**Comment by davsclaus** [comment]
No this option is only for the consumer. And its also identified as such in Apache Camel
https://github.com/apache/camel/blob/master/components/camel-vm/src/main/docs/vm-component.adoc

So the Camel IDEA plugin is correct as-is
