### ISSUE TITLE
Allow Ctrl-click navigation for <to uri=direct:... in Spring DSL

### ISSUE THREAD

**Issue by Bican007** [camel-tooling/camel-idea-plugin#480]
I could not find it maybe it is there. But would it be hard to have Ctrl-click navigation for <to uri=direct:.. ? 
I have projects where there are routes referenced and looking for a route by highlighting the uri and searching using Ctrl-Shitf-F is not optimal. :)
Thanks,
Radovan
`            <to uri="direct:orchestrationStart"/>
        </route>
`
directs to
`        <route id="orchestrationStart">
            <from uri="direct:orchestrationStart"/>
`

**Comment by davsclaus** [comment]
Maybe this PR will help with this
https://github.com/camel-tooling/camel-idea-plugin/pull/479

**Comment by Bican007** [comment]
Thank you. It will certainly help.

**Comment by fharms** [comment]
Solved in #479
