### ISSUE TITLE
Allow code completion on direct routes after "direct:<caret>"

### ISSUE THREAD

**Issue by fharms** [camel-tooling/camel-idea-plugin#483]
The #479 enable code completion on `to("dire<caret>`and select from an existing list of  direct routes which is really nice. But we should also support completion after the "direct:"

```
 .to("direct:<caret>")
```

**Comment by fharms** [comment]
@rastislavpapp what do think ?

**Comment by rastislavpapp** [comment]
It should already work like that - at least it does for me:

![image](https://user-images.githubusercontent.com/7340256/56349702-5c843600-61c9-11e9-8635-325a10094436.png)

![image](https://user-images.githubusercontent.com/7340256/56349744-79b90480-61c9-11e9-8b7b-86229b8bd088.png)

Even the CamelEndpointNameCompletionExtensionIT test does test for this case.

**Comment by fharms** [comment]
You are right, not sure why it didn't yesterday.

**Comment by rastislavpapp** [comment]
It might have been because Intellij automatically suggests strings it sees in the given file, if the plugin is not active (not loaded yet, or something). It just happened to me.
