### ISSUE TITLE
Support for alternatives camel-k DSLs

### ISSUE THREAD

**Issue by lburgazzoli** [camel-tooling/camel-idea-plugin#508]
In Apache Camel K we have support for a groovy and kotlin DSLs and it would be nice to have them supported by the camel-idea-plugin.

Some very simple examples:
- https://github.com/apache/camel-k-runtime/blob/master/camel-k-runtime-groovy/src/test/resources/routes.groovy
- https://github.com/apache/camel-k-runtime/blob/master/camel-k-runtime-kotlin/src/test/resources/routes.kts

The two additional DSLs are pretty much the same as the Java DSL and the main difference is that you can avoid all the ceremony needed to create a simple route (extending a class, implementing a method) and you cna start your route straight from a `from`

**Comment by davsclaus** [comment]
Logged ticket: https://github.com/camel-tooling/camel-idea-plugin/issues/509

**Comment by davsclaus** [comment]
Unfortunately that would be much extra work to take on - the plugins for eclipse / vscode etc would have Camel K support and other languages.
