### ISSUE TITLE
IDE: classType is a custom option that is not part of the Camel component

### ISSUE THREAD

**Issue by gurpal2000** [camel-tooling/camel-idea-plugin#530]
Using plugin version 0.6.2 in IntelliJ 2019.2.4

The following code flags up as a "issue" in the IDE as **classType is a custom option that is not part of the Camel component**

`.toD("dataformat:${header.strategy}:unmarshal?classType=${header.model}")`

Is it because the IDE cannot infer just from the placeholder (eg. when it is bindy-csv)?

**Comment by davsclaus** [comment]
Ah yeah thanks, dataformat should have lenient options. What version of Camel do you use in that project where you see this?

**Comment by gurpal2000** [comment]
Hi it was in IntelliJIdea2019.3 (Ultimate and earlier). I only have Community version now (2020.1) and can't test as 0.6.3 plugin version isn't compatible. But generally, it was happening in all prior 2019.x versions.

The context was like so:

```
.split(body().tokenize("\n")).streaming().executorService(Executors.newFixedThreadPool(applicationConfig.getSplitPoolSize()))
        .toD("dataformat:${header.importItem.strategy}:unmarshal?classType=${header.importItem.model}")
        .bean(mainProcessor, "convertObjectToMap")
        .bean(mainProcessor, "addBatchInfo")
        .to("direct:persist")
      .end()
```

The idea was to define profiles of different types of files in app config and that included the type of strategy needed. eg.

```
    - filename: dev_employees_salary.tsv
      charset: UTF-8
      strategy: bindy-csv
      model: com.gurpal.demo.model.Salary
      table: public.department_salary
```

**Comment by davsclaus** [comment]
Thanks what version of Camel did you use?

**Comment by gurpal2000** [comment]
At the time it was 3.0.0 (but i remember it happened in the 2.x version before the 3.0.0 came out).

**Comment by davsclaus** [comment]
You can turn on|off this warning in the settings for the plugin with: highlight custom .. as warnings
