### ISSUE TITLE
Add the support for Camel 3.0 once is released

### ISSUE THREAD

**Issue by omarsmak** [camel-tooling/camel-idea-plugin#532]
Currently the plugin supports Camel version `2.24.2`, once Camel 3.0 is officially released, I think it will make sense to add the support for Camel 3.0.

**Comment by apupier** [comment]
Camel 3.1 has been released.
With Camel 3.1, there is an API break affecting the plugin. JSonSchemahelper has been removed.

See https://github.com/camel-tooling/camel-tooling-common/pull/64 for the kind of modification to do

**Comment by davsclaus** [comment]
Yeah do a release first with Camel 2.25.1 and then later we can look at 3.x support

**Comment by fharms** [comment]
@davsclaus I'm working on the upgrade to Camel 3 and have a test that is testing validation of simple expression.

```Java
return "import org.apache.camel.builder.RouteBuilder;\n"
            + "public class MyRouteBuilder extends RouteBuilder {\n"
            + "        public void configure() throws Exception {\n"
            + "              from(\"direct:start\")\n"
            + "                .loopDoWhile(simple(\"${body.length} <error descr=\"Unexpected token =\">=!=</error> 12\"))\n"
            + "                .to(\"mock:loop\")\n"
            + "                .end()\n"
            + "                .to(\"mock:result\");"
            + "        }\n"
            + "    }";
```

This test routes used to return it has an `Unexpected token =`, but the `catalogService.validateLanguageExpression(loader, "simple", text);` is returning it is successfully validated. 

Is that expected with Camel 3?

**Comment by davsclaus** [comment]
No the validation should fail as `=!=` is not a valid operator

**Comment by davsclaus** [comment]
It can be something else, do you have camel-core-languages on the classpath

**Comment by davsclaus** [comment]
It works in apache camel
https://github.com/apache/camel/commit/4e32c389c3f7fd5fab628070e2a9a5f96a117f16
