### ISSUE TITLE
Support Intellij 2019.3

### ISSUE THREAD

**Issue by rastislavpapp** [camel-tooling/camel-idea-plugin#542]
Hello, I can't use 0.6.x version of the plug-in in 2019.3 - it only shows version 0.5.6. I know that there is 2019.3.1 and that the 0.6.x version works there, but I do not have control over my work computer's installed software and can therefore only use 2019.3 at the moment.

**Comment by fharms** [comment]
@rastislavpapp I'm closing this since we are passed version 2019. If you need it to work with 2019 you can checkout the project at change the version number and build the plug-in manual instead and install it as local plugin.
