### ISSUE TITLE
Quick documentation of Camel endpoint should also show resolved property values

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#55]
If you have an endpoint that uses property placeholders, then it would be nice if the quick document can show the resolved value as well. So you can see what value it was configured as.

In this example we have `foo.properties` with `myDelay=3000` which you cannot see in the quick docs (ctrl + j)
![screen shot 2017-01-01 at 7 05 53 pm](https://cloud.githubusercontent.com/assets/477100/21582380/57b99988-d055-11e6-80d5-0c8331cb79e6.png)

**Comment by davsclaus** [comment]
We should probably show both `{{myDelay}}` and then the resolved value as well. But how to do this in a nice way?

**Comment by davsclaus** [comment]
This would also require somehow the properties placeholder code we have today can have an api to resolve a placeholder value.

**Comment by jana007** [comment]
I was looking for this feature today, I'd be happy to look into adding the feature :)

**Comment by fharms** [comment]
@jana007 That's great and feel free to start hacking on the plugin.  If look into the `CamelPropertyPlaceholderSmartCompletionExtension`you can see how we search for property files and resolve values. You might have to refactor part of it to make it more shareable with other classes 

If you need help please let us know.

**Comment by bennetelli** [comment]
IMO it's not a beginners task. 
In CamelPropertyPlaceholderSmartCompletionExtension class we have to the logic of addCompletions() method which is not that easy to reuse because this code needs an instance of CompletionResultSet resultSet.
