### ISSUE TITLE
Invalid error for comment in route definition

### ISSUE THREAD

**Issue by kullmanp** [camel-tooling/camel-idea-plugin#557]
I have a rout like this:
```
from("jpa://ch.basler.ecm.archivenotifier.entity.ArchivEvent" +
        "?consumeDelete=false" +  // just update the entity by calling the @Consumed method
```
IntelliJ shows the error "Invalid boolean value: false" // just update the entity by calling the @Consumed method"

The error goes away if I remove the comment.

**Comment by davsclaus** [comment]
Cannot reproduced this with latest 0.7.x
