### ISSUE TITLE
Support IntelliJ 2020.2

### ISSUE THREAD

**Issue by pioto** [camel-tooling/camel-idea-plugin#560]
Same general issue as #545, #542, #512, #501, #492, etc.

When upgrading to the just-released IntelliJ 2020.2 release, the plugin is disabled, because it is marked as no longer compatible.

Aside from Lombok (e.g. https://github.com/mplushnikov/lombok-intellij-plugin/issues/840), this is the only plugin I see consistently having this issue with every new IntelliJ release, but perhaps I'm mostly just using 1st party plugins.

**Comment by Nosbielc** [comment]
news feed ?

**Comment by pioto** [comment]
@Nosbielc, I'm sorry, can you explain what you mean?

I don't see any sort of news feed for this project in particular.

I also don't see any version listed on https://plugins.jetbrains.com/plugin/9371-apache-camel-idea-plugin that supports 2020.2, other than the much older 0.5.6 release from 2018? Seems like newer versions have much more narrowly scoped IntelliJ version restrictions, which are likely at issue here.

**Comment by fharms** [comment]
Thanks for reporting this. It’s correct that we have released the plug-in to a very specific IDEA version so far. We might consider changing this with the work of upgrading to support Camel 3, but I can’t say when this will happen at the moment.

What you can do now is to checkout the repository and try to change the version in build.gradle https://github.com/camel-tooling/camel-idea-plugin/blob/master/camel-idea-plugin/build.gradle#L26 and build the plugin. Then you will be able to install plugin from disk instead

**Comment by davsclaus** [comment]
I tried to upgrade but got some IDEA test errors about Mock-JDK8 not found during testing.

**Comment by fharms** [comment]
there are several breaking changes with the upgrade to 2020.2. I have fixed
them with the upgrade to camel 3

fre. 31. jul. 2020 06.56 skrev Claus Ibsen <notifications@github.com>:

**Comment by michaelgarde** [comment]
Are there any updates regarding this? I just noticed today, that I'm using the old version 0.5.6 rather than 0.6.4. I'm also running Intellij Idea (Ultimate) 2020.2

**Comment by hakuseki** [comment]
Trying to build for 202 but the gradle task reverts:

```
> Task :camel-idea-plugin:patchPluginXml
[gradle-intellij-plugin :camel-idea-plugin:patchPluginXml] Patching plugin.xml: attribute `since-build=[202.7319.50]` of `idea-version` tag will be set to `201.6668`

```

Why is it resetting to 201?

**Comment by hakuseki** [comment]
Tons of errors in unit tests.
246 tests completed, 214 failed

IllegalArgumentExceptions mostly

Anything related you @fharms can tel me about?

**Comment by hakuseki** [comment]
I managed to fix the MockJDK-8 by changing to test methods to use @davsclaus 

Hardcoded the Java8 option since it was already hardcoded using the ```languageLevel``` property

```java
// return JavaSdk.getInstance().createJdk( "java " + compilerOption, BUILD_MOCK_JDK_DIRECTORY + compilerOption, false );
   return JAVA_8.getSdk();
```

**Comment by fharms** [comment]
I have that problem to with my work with the upgrade to Camel 3, and still have a few unit test failing.

I solved the issue you mention with the code below

```
@NotNull
@Override
protected LightProjectDescriptor getProjectDescriptor() {
 LanguageLevel languageLevel = LanguageLevel.JDK_1_8;
 return new DefaultLightProjectDescriptor() {
 @Override
 public Sdk getSdk() {
 return IdeaTestUtil.getMockJdk18();
 }

 @Override
 public void configureModule(@NotNull Module module, @NotNull ModifiableRootModel model, @NotNull ContentEntry contentEntry) {
 model.getModuleExtension( LanguageLevelModuleExtension.class ).setLanguageLevel( languageLevel );
 }
 };
}
```

**Comment by hakuseki** [comment]
I have now _highlight_ test errors:

```junit.framework.AssertionFailedError: Expect to find the (beanTestData, "myOverLoadedBean2") in the list of highlight```

any ideas?

**Comment by fharms** [comment]
@hakuseki  I can see it's actually the same tests I haven't solve in my branch yet https://github.com/camel-tooling/camel-idea-plugin/compare/master...fharms:feature/upgrade_to_camel3?expand=1

**Comment by hakuseki** [comment]
Ok. I have no idea about these either and their purpose other than they are suppose to validate.

**Comment by fharms** [comment]
The tests validate the Camel route build syntax for `bean` eg `.bean(beanTestData, "myOverLoadedBean(${body})")`

The code that is responsible for "validate" is the [annotator](https://github.com/camel-tooling/camel-idea-plugin/tree/master/camel-idea-plugin/src/main/java/com/github/cameltooling/idea/annotator)

**Comment by hakuseki** [comment]
Yes, true, but the underlying interface from IntelliJ is a little mistery to me…

**Comment by hakuseki** [comment]
Well, I can't get any further. I have no knowledge of the underlying IntelliJ features for this _highlight_ thing.
I see what it tries to accomplish but the underlying IntelliJ logic is too much atm.

**Comment by davsclaus** [comment]
Upgrading to latest IDEA
