### ISSUE TITLE
Error with activemq endpoint destination option

### ISSUE THREAD

**Issue by Greenev** [camel-tooling/camel-idea-plugin#566]
Hello, everyone!
I have a trouble setting destination options for activemq endpoint - http://activemq.apache.org/destination-options.html
Here is the route where I would like to disable consumers prefetch, however I am getting an error "Unknown option" in my idea
```
<route id="from.amq">
    <from uri="activemq:myqueue?destination.consumer.prefetchSize=0"/>
    ...
</route>
```

**Comment by davsclaus** [comment]
The option needs to be added to camel-activemq
https://issues.apache.org/jira/browse/CAMEL-16568
