### ISSUE TITLE
Can't install newer plugin version (only 0.5.6 available) in IntelliJ 2020.3

### ISSUE THREAD

**Issue by d-a-gerashenko** [camel-tooling/camel-idea-plugin#576]
I can't install Apache Camel IDEA Plugin 0.6.4 in IntelliJ 2020.3.
Installation works only for 0.5.6.

**Error:** Plugin 'Apache Camel IDEA Plugin' (version '0.6.4') is not compatible with the current version of the IDE, because it requires build 201.* or older but the current build is IU-203.5981.155

**Latest release info:**
Version: 2020.3/**Build: 203.5981.155**/1 December 2020: https://www.jetbrains.com/idea/download/

**My build info:**
IntelliJ IDEA 2020.3 (Ultimate Edition)
Build #IU-203.5981.155, built on December 1, 2020
Licensed to Dmitriy Geraschenko
Subscription is active until May 27, 2021
Runtime version: 11.0.9+11-b1145.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1965M
Cores: 8
Non-Bundled Plugins: com.layoutmanager, Osmorc

**Comment by d-a-gerashenko** [comment]
I solved this problem.
Download: https://plugins.jetbrains.com/plugin/9371-apache-camel-idea-plugin/versions
Change "201." to "203." in camel-idea-plugin-0.6.4.zip\camel-idea-plugin\lib\camel-idea-plugin-0.6.4.jar\META-INF\plugin.xml

**Comment by vnnegt** [comment]
is this a legitimate fix? i thought 0.5.6 was the last compatible plugin version for intellij 2020 and above.

**Comment by davsclaus** [comment]
We dont have the time to work on this so much, and Jetbrains changed how plugins are compatible, so they get stale much quicker.

Their API is horrendous to develop plugins for, and it's a pain to keep maintaining.

**Comment by javaduke** [comment]
I tried this hack, but IntelliJ just hangs when I enable plugin and open project. IDEA 2020.3.

**Comment by d-a-gerashenko** [comment]
[camel-idea-plugin-0.6.4.zip](https://github.com/camel-tooling/camel-idea-plugin/files/5757332/camel-idea-plugin-0.6.4.zip)

**Comment by FrankyGee** [comment]
@d-a-gerashenko's fix worked for me with IntelliJ 2020.3.1 & Camel 3.4.4 - so far. IDE has loaded 3 modules using Camel, and there are no plugin errors showing. Gutter icons & links between routes are working, but autocomplete of String endpoints is not.

**Comment by d-a-gerashenko** [comment]
@FrankyGee try File->Invalidate Caches->Invalidate and Restart

**Comment by FrankyGee** [comment]
@d-a-gerashenko That worked, thanks. 

Is the implication that the plugin works just fine, it's only the version check getting in the way? I'm wary of the troubles with #560. If it's that straight forward I'm happy to have a crack at updating & testing the source, but I can't help but feel I'm missing something.

**Comment by d-a-gerashenko** [comment]
I have been using my patched plugin for about 5 months and it works acceptable. Sometimes autocomplete doesn't work but I fix it with restarting. It's better than nothing.

**Comment by davsclaus** [comment]
Next release will run on latest IDEA
