### ISSUE TITLE
camel-main - Add support for completions in properties file

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#594]
<img width="598" alt="Screenshot 2021-04-28 at 11 15 26" src="https://user-images.githubusercontent.com/477100/116379169-0b28cb80-a813-11eb-8e39-eac480b0f7c1.png">

**Comment by davsclaus** [comment]
We have in camel-catalog an API for validating those camel-main configuration options. That can work similar to uri validation, with list of possible values and so on.

**Comment by davsclaus** [comment]
One tick is that we support both dashed and camelCase, eg bean-introspection-logging-level vs whats in the screenshot above

**Comment by apupier** [comment]
not sure it can be easily adapted but in case it is reusable, entry point for corresponding code for this functionality in Camel Language Server is https://github.com/camel-tooling/camel-language-server/blob/269877f251bb3bf1e15e8553accf0593f4501e07/src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelComponentPropertyKey.java#L60

it handles the dashed vs camelCase

**Comment by essobedo** [comment]
Sounds like a duplicate of https://github.com/camel-tooling/camel-idea-plugin/issues/684? If so it is fixed now

**Comment by davsclaus** [comment]
Yes its a duplicate
