### ISSUE TITLE
Endpoint Completion Camel Quarkus

### ISSUE THREAD

**Issue by nek4life** [camel-tooling/camel-idea-plugin#605]
I'm using Idea 2021.1 with Camel Quarkus and I'm not seeing any endpoint completion of the endpoint or the options. I do have Java completion for to() from() log() etc... I created a new project from scratch with the intellij quarkus project wizard and added camel quarkus dependencies and one route to demonstrate the issue.

[demo.zip](https://github.com/camel-tooling/camel-idea-plugin/files/6420852/demo.zip)

**Comment by davsclaus** [comment]
Can you close and open the project as the IDEA plugin only detects on project open if Camel is present

**Comment by davsclaus** [comment]
<img width="1389" alt="Screenshot 2021-05-04 at 14 02 06" src="https://user-images.githubusercontent.com/477100/117000409-521a3380-ace1-11eb-8d75-112e92521670.png">

works for me

**Comment by davsclaus** [comment]
Related to https://github.com/camel-tooling/camel-idea-plugin/issues/606

**Comment by nek4life** [comment]
I tried opening and closing the project as you suggested as well as invalidated my caches and I still do not have auto completion. I'm also realizing after viewing your screenshot that I am missing the camel gutter icon as well.

**Comment by davsclaus** [comment]
And you are using v0.7.4 of the Camel plugin? And is it IDEA 2021.1 release?

**Comment by nek4life** [comment]
I have to apologize it appears somehow the camel plugin was removed from my installation. I am now seeing the gutter icon. However, the auto completion is not coming up as I type. Do I need to invoke a key command for the autocompletion to display?

I'm using 0.7.4 and 2021.1.1

<img width="524" alt="Screen Shot 2021-05-04 at 8 34 22 AM" src="https://user-images.githubusercontent.com/16930/117004049-9db5e880-acb3-11eb-8062-ea21b2f361d1.png">

Should I expect a list when my cursor is placed as shown?

I am seeing documentation if I place my mouse cursor over the text as well now.

**Comment by davsclaus** [comment]
Yes press ctrl + space should list the options as I do. You can also try to remove period=5000, and place the cursor after the ? mark and do ctrl + space. 

Also ctrl + space works for the values, eg after =.

**Comment by nek4life** [comment]
Thank you, Claus! That was it. I needed to invoke the action. I usually invoke auto completion when suggestions appear when typing and have never uses this key combination. Thank you so much for your help. I recently bought your book and am excited to learn Apache camel! This plugin will help with the large number of options available on each endpoint.
