### ISSUE TITLE
Detect if Camel is added later to an existing project

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#606]
Currently this plugin can only detect if its a Camel project when the project is opened in IDEA.
But you may create a project and then add Camel later. 

Then you would need to close project and open again to make Camel be detected.

Maybe we can hook into a listener if the JARs are changed in the classpath (library in IDEA terms) and detect that way.

**Comment by essobedo** [comment]
This problem also occurs when a Camel project is opened for the first time since on projectOpened IDEA doesn't yet see any modules so any dependencies

**Comment by essobedo** [comment]
The related PR https://github.com/camel-tooling/camel-idea-plugin/pull/706
