### ISSUE TITLE
Better Camel 2.x support for the 0.7.x version of the plugin

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#607]
Camel 2.x components does not have so rich metadata, so the plugin needs to do more `!= null` checks and some options that are only on 3.x to be skipped for 2.x.

**Comment by BoBoWalker** [comment]
I think I have what
you are looking for! Let me get back

**Comment by davsclaus** [comment]
Fixed some stuff for 0.7.5, lets get more community feedback
