### ISSUE TITLE
Debugger - Support Set Value in right menu

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#655]
<img width="1533" alt="Screenshot 2022-01-07 at 10 17 39" src="https://user-images.githubusercontent.com/477100/148521544-4d034d31-a2aa-415f-8e13-fd84aaf2f0e8.png">

The body is a String type, and when you right click then "Set Value ..." is disabled. It would be good to support this, and set the value back as the same type.

**Comment by essobedo** [comment]
The corresponding PR https://github.com/camel-tooling/camel-idea-plugin/pull/762
