### ISSUE TITLE
Cannot set breakpoint if the parent class is not called RouteBuilder

### ISSUE THREAD

**Issue by vemod** [camel-tooling/camel-idea-plugin#669]
Cannot set breakpoint in the route because parent class is not called `RouteBuilder`.
We have following case.
```
class MyRouteBuilder extends MyBaseRouteBuidler() { from(customThing)....}
class MyBaseRouteBuilder extends org.apache.camel.builder.RouteBuilder  { public RouteDefinition from(MyCustom custom) {return this.from(custom.getEndpoint()); }}
```
In this case we are not able to set camel breakpoint because out parent class is not called RouteBuilder or any of the ones in this list
https://github.com/camel-tooling/camel-idea-plugin/blob/050611903839824b3caf030d47ae73c2b7055f1b/camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/extension/camel/JavaCamelIdeaUtils.java#L59

But if I rename `MyBaseRouteBuilder` to `RouteBuilder` it works
```
class MyRouteBuilder extends RouteBuilder() { from(customThing)....}
class RouteBuilder extends org.apache.camel.builder.RouteBuilder.RouteBuilder  { public RouteDefinition from(MyCustom custom) {return this.from(custom.getEndpoint()); }}
```
its not even a regex matcher but class name string matcher without package.
Is it possible to fix the plugin to support inheritance properly or use regex matcher?

https://camel.zulipchat.com/#narrow/stream/258729-camel-tooling/topic/Intellij.20plugin.2C.20cannot.20set.20breakpoint

**Comment by javaduke** [comment]
Fixed: https://github.com/camel-tooling/camel-idea-plugin/pull/672
