### ISSUE TITLE
Option name and value completion in properties files

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#684]
It would be good to have support for end users configuring their application.properties

All the main config is possible to use,
https://camel.apache.org/components/3.16.x/others/main.html

```
camel.main.messageHistory=true
```

Also this works for all the components, so you can do

```
camel.component.seda.queueSize=50
```

We have all the options listed in camel-catalog so it should be possible to find out which options are available, what type they are, default values, enums and so on. Like we do for endpoint uri completions.

**Comment by davsclaus** [comment]
@essobedo if you want to keep being awesome and hack on the camel idea plugin, then this ticket would be great to have

**Comment by essobedo** [comment]
@davsclaus no problem, I can have look with pleasure.

**Comment by essobedo** [comment]
@davsclaus you can assign it to me

**Comment by davsclaus** [comment]
@essobedo I invited you to the camel-tooling group - I assume that when accepted you can self assign tickets and so on

**Comment by essobedo** [comment]
@davsclaus I accepted but I still can't, only people with write access to a repository can assign issues and I can't so I guess that they are 2 separate things
