### ISSUE TITLE
application.properties - Code assistance to show popup documentation

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#692]
In Camel endpoint URIs we can show docs with ctrl + j as a popup window (see below)
<img width="1472" alt="Screenshot 2022-05-14 at 09 47 52" src="https://user-images.githubusercontent.com/477100/168416364-75ebd7d1-9a7f-4116-8e40-16bd5e8e2fe4.png">

Would be good to have the same for application.properties

<img width="830" alt="Screenshot 2022-05-14 at 09 48 56" src="https://user-images.githubusercontent.com/477100/168416381-c79fb42c-d5f8-47ff-ab3b-bca8ceac9251.png">

**Comment by davsclaus** [comment]
@essobedo having doc popup would be great

**Comment by essobedo** [comment]
Ok no problem, good idea, I will check that tomorrow

**Comment by essobedo** [comment]
The corresponding PR https://github.com/camel-tooling/camel-idea-plugin/pull/693
