### ISSUE TITLE
Code assistance for kamelets

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#697]
See the example
https://github.com/apache/camel-examples/tree/main/examples/kamelet-chucknorris

If you edit the route

    <from uri="kamelet:chuck-norris-source"/>

Then you should be able to add `?` and then press ctrl + space and see the list of options you can configure on the `chukc-norris-source` kamelet.

**Comment by davsclaus** [comment]
We should include the camel-kamelets-catalog JAR in the dist so we can support the OOTB kamelets from ASF. And for custom kamelets then we need to discover these from the project.

**Comment by davsclaus** [comment]
@essobedo if you want another task to work on for this tool, then code completion for kamelets would be great.

You can add the camel-kamelet-catalog JAR that has all kamelets inside in the `kamelet` folder. There are the kamelet spec yaml files, where you can find every option a kamelet support, and what type, default value, enum, description etc. Similar to what we have for camel endpoints, but stored in a yaml file instead of json.

**Comment by davsclaus** [comment]
The kamelet catalog is in maven repo
https://repo.maven.apache.org/maven2/org/apache/camel/kamelets/camel-kamelets-catalog/

**Comment by davsclaus** [comment]
There is also a java api you can maybe use
https://github.com/apache/camel-kamelets/blob/main/library/camel-kamelets-catalog/src/main/java/org/apache/camel/kamelets/catalog/KameletsCatalog.java

**Comment by davsclaus** [comment]
And maybe the KameletsCatalog API need enhancements if you find out it lacks some functionality you need.

**Comment by essobedo** [comment]
@davsclaus yeah of course with pleasure. This before the code completion of application.yaml for Spring Boot users?

**Comment by davsclaus** [comment]
Oh yeah maybe its better to complete the yaml first so this feature is complete before working on kamelets.

**Comment by essobedo** [comment]
The corresponding PR https://github.com/camel-tooling/camel-idea-plugin/pull/709
