### ISSUE TITLE
Can not install on the latest EAP to test with the new IDEA UI

### ISSUE THREAD

**Issue by mgubaidullin** [camel-tooling/camel-idea-plugin#707]
Can not install on the latest EAP to test with the new IDEA UI

<img width="529" alt="Screen Shot 2022-06-06 at 9 59 56 AM" src="https://user-images.githubusercontent.com/1379213/172175954-d3ebd439-c7ca-444a-99ce-0e387baf27e0.png">

**Comment by davsclaus** [comment]
Try with 0.8.10 release

**Comment by mgubaidullin** [comment]
Confirm
