### ISSUE TITLE
not use press ctrl+space

### ISSUE THREAD

**Issue by chaun85** [camel-tooling/camel-idea-plugin#717]
install this plugin on macos or windows not use,bug ctrl+j can use<img width="958" alt="image" src="https://user-images.githubusercontent.com/99258257/173850957-e3e73c3a-5add-466f-911d-1a981316249d.png">
shortcut key ctrl + space conflict,how can ?

**Comment by davsclaus** [comment]
You can reconfigure shortcut keys in IDEA and also on your mac OS itself.

**Comment by davsclaus** [comment]
For example I have disabled ctrl + space on my mac
<img width="646" alt="Screenshot 2022-06-15 at 21 33 12" src="https://user-images.githubusercontent.com/477100/173909463-2ddea0f5-c0e7-4d53-8701-4117b2208c2a.png">

**Comment by birkh8792** [comment]
thanks
disabled ctrl + space on my mac not use.
how can reconfigure shortcut keys in IDEA?

**Comment by essobedo** [comment]
In Preferences... / Keymap

![image](https://user-images.githubusercontent.com/1618116/174037378-b2210c49-3657-4371-a60b-41a35b49ddfc.png)
