### ISSUE TITLE
Mention requirements in readme

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-idea-plugin#721]
it would be nice to mention the requirements in readme. Like for instance the version of Camel required to use the debug feature in the extension.

**Comment by davsclaus** [comment]
See
https://github.com/camel-tooling/camel-idea-plugin/wiki/How-to-use-the-Camel-Debugger

**Comment by davsclaus** [comment]
The link in the bottom of the readme points to the FAQ where you have link to debugger
