### ISSUE TITLE
Camel Debugger variables not updated on set value

### ISSUE THREAD

**Issue by essobedo** [camel-tooling/camel-idea-plugin#734]
When we set a value using the dedicated UI, the value is took into account by Camel but the  Camel Debugger variables are not refreshed consequently as we can see in next screenshot:

![variables-not-updated-on-set-value](https://user-images.githubusercontent.com/1618116/177950811-2842cb5f-5423-42b9-afc1-beab9f292ad9.gif)

**Comment by essobedo** [comment]
The problem doesn't seem to come from the plugin itself but it looks like the `BacklogDebugger` in Camel doesn't reflect the changes in the `BacklogTracerEventMessage` only on the `SuspendedExchange`.

**Comment by essobedo** [comment]
Should be fixed by https://issues.apache.org/jira/browse/CAMEL-18260

**Comment by davsclaus** [comment]
Fixed when we upgrade Camel #739
