### ISSUE TITLE
Camel debugger should not be added if its disabled

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#749]
<img width="939" alt="Screenshot 2022-10-28 at 09 19 54" src="https://user-images.githubusercontent.com/477100/198527441-bc77e68b-74f4-464f-908a-9a9b16899bec.png">
<img width="658" alt="Screenshot 2022-10-28 at 09 19 21" src="https://user-images.githubusercontent.com/477100/198527445-0601f836-9cf6-4174-8ce6-807d48bd253a.png">

**Comment by essobedo** [comment]
The corresponding PR https://github.com/camel-tooling/camel-idea-plugin/pull/756
