### ISSUE TITLE
Use Apache Maven APIs for downloading artifacts

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#751]
In camel-catalog-maven we use groovy grape to download catalog JARs from the internet
https://github.com/apache/camel/tree/main/catalog/camel-catalog-maven

We may want to switch to use apache maven directly, like we recently did in camel-jbang. Its more complex code to do so, but we can maybe make the camel-jbang code in a common JAR that camel-catalog-maven and camel-jbang both can share.

Then the IDEA plugin can use that for download too.

By using Apache Maven directly, then its standard and it also supports the .m2/settings.xml file from the user where they can setup proxy / auth and whatnot.

**Comment by davsclaus** [comment]
See #747

**Comment by davsclaus** [comment]
Apache Camel will come with a better maven downloader in camel-catalog-maven which comes in 3.21 / 4.0
https://issues.apache.org/jira/browse/CAMEL-11767

**Comment by davsclaus** [comment]
There will be a new `camel-tooling-maven` from Camel 3.21 onwards we can use.

**Comment by davsclaus** [comment]
See #884

**Comment by kobmik** [comment]
Thanks for the new release. Unfortunately, Maven downloader in version 1.1.0 doesn't work for me. I've added the third party repository to my pom.xml.
It seems that CamelService finds the repository in pom.xml, but still wants to download the catalog from the repo.maven.org.
(Maven repo is blocked in our company)

INFO - #com.github.cameltooling.idea.service.CamelService - Found third party Maven repository id: central url:https://artifactory...
FINE - #com.github.cameltooling.idea.service.CamelMavenVersionManager - Trying to load the catalog version: 3.21.1
WARN - #com.github.cameltooling.idea.service.CamelMavenVersionManager - Could not load the catalog version 3.21.1: org.apache.camel.tooling.maven.MavenResolutionException: The following artifacts could not be resolved: org.apache.camel:camel-catalog:jar:3.21.1 (absent): Could not transfer artifact org.apache.camel:camel-catalog:jar:3.21.1 from/to central (https://repo1.maven.org/maven2)...

**Comment by essobedo** [comment]
@kobmik thx for the quick feedback, please create a ticket to describe your problem
