### ISSUE TITLE
Cannot start maven project on Windows

### ISSUE THREAD

**Issue by MantasG6** [camel-tooling/camel-idea-plugin#760]
Apache Camel IntelliJ plugin throws error like that when trying to build maven project on windows. Anyone know how to fix this? change some configuration, path, anything?

java.lang.RuntimeException: java.nio.file.InvalidPathException: Illegal char <:> at index 2: \C:\Users\mantasg\.groovy\grapes\org.apache.camel.springboot\camel-debug-starter\jars\camel-debug-starter-3.18.2.jar

**Comment by essobedo** [comment]
The corresponding PR https://github.com/camel-tooling/camel-idea-plugin/issues/760
