### ISSUE TITLE
IDEA 2022.2.3 ultimate compatible issues

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#775]
<img width="1410" alt="Screenshot 2022-11-21 at 10 20 05" src="https://user-images.githubusercontent.com/477100/203012765-fb253665-8281-4f63-88e9-52f4b3b8f8b4.png">
<img width="1191" alt="Screenshot 2022-11-21 at 10 20 14" src="https://user-images.githubusercontent.com/477100/203012779-d6f38bdb-88d5-4204-ad7a-36b46b42e08e.png">

**Comment by korkutkose** [comment]
And possibly for idea 2022.3.x. Plugin cannot be installed on latest version of ide.

**Comment by davsclaus** [comment]
See also #788

**Comment by davsclaus** [comment]
You can see this report on their website
https://plugins.jetbrains.com/plugin/9371-apache-camel/versions
