### ISSUE TITLE
IDEA 2022.3.x support

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#788]
This version has breaking changes so its a bit tougher to support

@essobedo I pushed the build files to upgrade to latest IDEA 2022.3.x.
The older 2022.1 and 2022.2 works, but 2022.3 has many compile error. So it seem JetBrains did some bigger changes there.
I still think we need to move forward, so we may end up with 2022.3 as the minimum version if we cannot make it work with older versions as well.

**Comment by essobedo** [comment]
Fixed by https://github.com/camel-tooling/camel-idea-plugin/pull/801
