### ISSUE TITLE
Support for IntelliJ IDEA 2022.3.X

### ISSUE THREAD

**Issue by vladmangra** [camel-tooling/camel-idea-plugin#805]
Hello. When I try to install the latest plugin version (v.0.9.0), i get the following error:

![plugin_error](https://user-images.githubusercontent.com/26487847/224310854-890cef52-3d2d-4ea3-a674-f46d5f2f3506.PNG)

Could you please add support for IDEA version 2022.3 ?

**Comment by davsclaus** [comment]
There is a commit already
https://github.com/camel-tooling/camel-idea-plugin/commit/580acaf2e2228abc48c48ae4d61ff3ebb8873a88

**Comment by vladmangra** [comment]
@davsclaus Is there a new release scheduled in the near future (that includes this commit) ?

**Comment by davsclaus** [comment]
There is a new 0.9.1 release out

**Comment by vladmangra** [comment]
@davsclaus Thank you Claus for the information.
