### ISSUE TITLE
Plugin requests "update" to v0.5.5

### ISSUE THREAD

**Issue by lex-divert** [camel-tooling/camel-idea-plugin#816]
Each time JetBrains releases a new build that's outside the specified-compatible range for the plugin, the IDE disables the plugin (as expected) and offers an "update" to v0.5.5 from 2018.

The list of previous versions offers an explanation: the specified-compatible range for v0.5.5 is "2016.2 +", with no maximum ( [JetBrains link](https://plugins.jetbrains.com/plugin/9371-apache-camel/versions/stable/49711) ). All plugin builds since then have specified a closed range (eg v0.5.8 has "2019.1.2 — 2019.1.4"). 

---
(This has been a problem for a long time, but I keep being too busy to write a detailed bug report and propose a solution. I'm submitting this brief note now because it's relevant again with IntelliJ 2023.1, and apologize for the lack of formality.)

**Comment by davsclaus** [comment]
IDEA now has version ranges so we need to set an end range

**Comment by davsclaus** [comment]
Upgrade to 0.9.4 that supports IDEA 2023.1
