### ISSUE TITLE
Is debugging in Camel Quarkus supported?

### ISSUE THREAD

**Issue by javaduke** [camel-tooling/camel-idea-plugin#820]
I have a Camel Quarkus application (in XML DSL) which I'm trying to debug, but when I run it, all breakpoints that I set in the code are disabled. I use Camel Quarkus Application runner, do I need to specify any additional parameters or profiles?
Forgot to mention, I use the latest version of the plugin, 0.9.4 and IntelliJ 2023.1

**Comment by essobedo** [comment]
IIRC, it should work since https://github.com/camel-tooling/camel-idea-plugin/pull/728. Do you have a reproducer to share?

**Comment by javaduke** [comment]
No, sorry, it's a proprietary code and I cannot share it. But I have several projects based on different versions of Camel (3.18, 3.20, etc) and they all show the same behavior. Again, the code is written using XML DSL, not Java DSL, maybe this is an issue?

**Comment by javaduke** [comment]
OK, I think I know what's happening. Even though I see that the Camel debugger is enabled, the IntelliJ still starts Ava debugger on a different port. In the console log I see: `Listening for transport dt_socket at address: 5005. Attach debugger` but even when I click on Attach debugger and it connects to port 5005, it switches back to the Java debugger.
Not sure how to address this.

**Comment by javaduke** [comment]
Oddly enough it doesn't stop at the Java breakpoints either (although it still shows them as Enabled). Is there anything specific I should have in my pom or application.yml? I use the Camel Quarkus Application run configuration, tried explicitly setting the profile `dev`, but nothing helps. Something is going on here...

**Comment by javaduke** [comment]
And here's what I see in the Breakpoints window:
![Screenshot 2023-04-13 at 1 48 27 PM](https://user-images.githubusercontent.com/561559/231879559-87d9ee74-c440-4d9e-a758-9da4c82df5c0.png)

**Comment by javaduke** [comment]
I ran the code in the debugger and what happens is the result of the xpath evaluate() is null, see here: https://github.com/camel-tooling/camel-idea-plugin/blob/main/camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerSession.java#L829

The path expression seems to be correct, e.g.:
`//*[@sourceLocation='file:/Users/eberman/Dev/demobank/target/classes/camel/accounts.xml' and @sourceLineNumber='10']` but the result is null.

**Comment by javaduke** [comment]
https://github.com/camel-tooling/camel-idea-plugin/pull/821

**Comment by davsclaus** [comment]
Thanks for the PR
