### ISSUE TITLE
Can't debug tests with plugin enabled

### ISSUE THREAD

**Issue by ai212983** [camel-tooling/camel-idea-plugin#824]
Hello guys. 

I'm experiencing a problem where tests debug fail to start in a project using Apache Camel when the plugin is active. 
However, when the plugin is disabled or the project doesn't use Apache Camel, everything works as expected. 

I've created an [IntelliJ IDEA ticket](https://youtrack.jetbrains.com/issue/IDEA-319001), but it seems the problem is on plugin side.

**System**
macOS Ventura 13.3.1 (22E261)
2,9 GHz Quad-Core Intel Core i7

**IDE**
IDEA build #IU-231.8109.175, built on March 28, 2023, 
Runtime version: 17.0.6+10-b829.5 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Apache Camel (0.9.5)

**Project setup**
Gradle 7.6.1
Amazon Corretto 1.8.0_312

**Comment by essobedo** [comment]
Hi, could you please provide steps to reproduce?

**Comment by ai212983** [comment]
@essobedo Like I've described in IntelliiJ ticket: 
- open a Gradle/Java project using Apache Camel (version 3.14.1, to be precise)
- open file with tests (JUnit 5.9.2), no Apache Camel functionality being actually tested
- select "Run 'TestingClass.testMethod'" from gutter button next to the test method. Test runs fine.
<img width="259" alt="Screenshot 2023-04-27 at 13 33 18" src="https://user-images.githubusercontent.com/87319/234849957-cd3cfe89-585e-4b8f-9491-a10ff7faba69.png">

- select "Debug 'TestingClass.testMethod'" from same gutter button. Nothing happens.

**Comment by flyasky** [comment]
+1 
debug button in IntelliJ unclickable when plugin is enabled.
also when I add breakpoint it asks me do I want 'camel' or 'java' breakpoint. maybe this is related somehow.

**Comment by essobedo** [comment]
Choose camel breakpoint. I will look into this next week

**Comment by essobedo** [comment]
IIRC gradle is not yet supported, only maven

**Comment by essobedo** [comment]
Closing it as it is a duplicate if https://github.com/camel-tooling/camel-idea-plugin/issues/641

**Comment by essobedo** [comment]
Reopening it as it is not a duplicate, it is not a feature but a bug
