### ISSUE TITLE
Support for Camel-4.0.0

### ISSUE THREAD

**Issue by chumpa** [camel-tooling/camel-idea-plugin#848]
Dear authors,

please disclosure is camel-4.0.0 in plans for support by your wonderful plugin? Currently on Ideaj ultimate 2023.1.2 and Camel-4.0.0-M3 the plugin version 0.9.6 doesn't work (no spring, just Default runtime provider over Main class).

**Comment by davsclaus** [comment]
are you using spring boot projects

**Comment by chumpa** [comment]
No any spring. Just console application (gradle plugins application and java), here is build.gradle.kts:
```
plugins {
    id("java")
    application
}

group = "org.example"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}
val camel_version = "4.0.0-M3"

dependencies {
    testImplementation(platform("org.junit:junit-bom:5.9.1"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    implementation("org.apache.camel:camel-core:$camel_version")
    //implementation("org.apache.camel:camel-http:$camel_version")
    implementation("org.apache.camel:camel-base:$camel_version")
    implementation("org.apache.camel:camel-main:$camel_version")
    implementation("org.apache.camel:camel-componentdsl:$camel_version")
    implementation("org.apache.camel:camel-xml-io-dsl:$camel_version")
    implementation("ch.qos.logback:logback-classic:1.4.7") //1.2.11
}
```

**Comment by davsclaus** [comment]
Ah yeah there is some code in the plugin that checks for camel v2 and v3. We need to add support for v4 as well.

**Comment by davsclaus** [comment]
@essobedo we need add support for Camel v4 and then we could bump the version to 1.0.x
And also drop Camel v2 support.

**Comment by essobedo** [comment]
Regarding the drop of the support of Camel v2 there is already a ticket for it https://github.com/camel-tooling/camel-idea-plugin/issues/648

**Comment by essobedo** [comment]
@chumpa Thank you for the feedback, this will be fixed very soon in v1
