### ISSUE TITLE
Camel-JBang - Auto-import dependencies

### ISSUE THREAD

**Issue by essobedo** [camel-tooling/camel-idea-plugin#850]
When using Camel-JBang, if we want to write a route using the Java DSL, for now we need to add manually the dependencies otherwise the class won't compile and the plugin won't allow adding "Camel Breakpoints"

**Comment by essobedo** [comment]
Related to https://github.com/camel-tooling/camel-idea-plugin/pull/849

**Comment by davsclaus** [comment]
I am not sure how easy this is, but we could try having jbang generate the list

camel dependency list --ignore-loading-error=true
