### ISSUE TITLE
Navigation to endpoints, bean methods, etc., not working

### ISSUE THREAD

**Issue by jeremyross** [camel-tooling/camel-idea-plugin#867]
A while back I lost the ability to navigate (cmd+b). Anyone else having this problem?

IntelliJ: 2023.1.2
Camel plugin: 0.9.9

![image](https://github.com/camel-tooling/camel-idea-plugin/assets/173087/2256887c-ac95-48f2-addb-342729ca2b9d)
![image](https://github.com/camel-tooling/camel-idea-plugin/assets/173087/a67fc413-fc64-4674-ae2d-64f4c0d00d4b)

**Comment by essobedo** [comment]
TBH I'm not really surprised since all the test cases related to those features seem to have been commented more than 2 years ago so if by chance it was still working recently, nothing prevented a potential regression to happen.

**Comment by essobedo** [comment]
Could you please provide a reproducer because it seems to work on my side as you can see in the screenshot below:

![navigator](https://github.com/camel-tooling/camel-idea-plugin/assets/1618116/84165f3f-957d-4e4a-93e2-d89fd75228ce)

**Comment by jeremyross** [comment]
I uninstalled, then reinstalled and everything in the world is good again. I suspect #665 can be closed also.

**Comment by essobedo** [comment]
Good news! Regarding #665, I've just tested it is still actual so it cannot be closed
