### ISSUE TITLE
Add more unit tests

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#91]
Look at adding some more tests using the idea api to test completions, intention etc.

**Comment by fharms** [comment]
Nice work @devclaus 👍😉

**Comment by davsclaus** [comment]
Now its likely you @fharms that is behind on unit tests ;)

**Comment by fharms** [comment]
Damn it :-) 

Well I gonna change that with the Annotator feature

**Comment by fharms** [comment]
Touchdown and the crowd goes wild. With this PR #127 @davsclaus I'm back

**Comment by davsclaus** [comment]
TODO: add unit test for preference

**Comment by davsclaus** [comment]
Not sure its easy to add doc test with smart completion where you simulate pressing ctrl + j, I dont know how to do that.

**Comment by davsclaus** [comment]
Ah found a little way so adding some tests now

**Comment by fharms** [comment]
Closing this since it is not relevant any more. The current level is sufficient and it's mandatory to add new test case for bug fix and new features
