### ISSUE TITLE
Camel XML - Support the new <camel> root tag

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#912]
```
<?xml version="1.0" encoding="UTF-8"?>

<camel>

	<!-- Write your routes here, for example: -->
    <route>
        <from uri="timer:xml?period={{time:1000}}"/>
        <setBody>
            <simple>Hello Camel from ${routeId}</simple>
        </setBody>
        <log message="${body}"/>
    </route>

</camel>
```

We have a new `<camel>` as root that that can have embedded `<route>` / `<rest>` elements.

**Comment by essobedo** [comment]
This should work out of the box as long as you define the default namespace in your root element as next:
```
<?xml version="1.0" encoding="UTF-8"?>
<camel xmlns="http://camel.apache.org/schema/spring">
...
```

**Comment by davsclaus** [comment]
okay, can you update camel-jbang so it has that namespace

**Comment by essobedo** [comment]
Do you mean that you would like me to modify the template used by Camel JBang to use `camel` as the root element with the namespace properly defined?

**Comment by essobedo** [comment]
Seems to be already done by https://issues.apache.org/jira/browse/CAMEL-19773

**Comment by davsclaus** [comment]
Ah okay
