### ISSUE TITLE
Code assistance for Camel K - Pipe YAML files

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#932]
What previously was known as `KameletBinding` is now `Pipe`.

See this example
https://github.com/apache/camel-kamelets-examples/tree/main/jbang/camelk-bind

The binding uses kamelets for the source/sink/steps and we should have code assistance in IDEA plugin, to list the options from the kamelet, and also help to auto complete kamelet names (from the kamelets catalog).

**Comment by davsclaus** [comment]
@essobedo in case you want to help and see if we can improve this - eg we in the yaml file, that this is Camel _stuff_

```
apiVersion: camel.apache.org/v1
kind: Pipe
```

And then we can show Camel icon in the gutter at the line with `Kind: Pipe`.

And for source/sink/step that has `Kamelet` as kind, then we can have code assistance.

**Comment by essobedo** [comment]
@davsclaus let me see what I can do
