### ISSUE TITLE
Custom Component JSON to Kamelets 

### ISSUE THREAD

**Issue by skumaravelan** [camel-tooling/camel-idea-plugin#960]
For custom component services, we have written components.json file and and have corresponding classes in the camel runtime to execute the integrations . I am trying to figure out a mechanism of using the custom components.json file, i would like to define an kamelet.yaml using any pre existing tools by camel. so that we can use those tools to convert to kamelet file and update as needed using a Karavan kind of visual tool.  I understand that these are two different ways of executing the components. As Karavan supports kamelet it works elegantly when we have these files converted using a camel cli or something along those line. Any suggestion on this front would help.

**Comment by davsclaus** [comment]
Sorry but this is the Camel IDEA plugin project and not Apache Camel Karavan.

You should ask at in their discusssion
https://github.com/apache/camel-karavan
