### ISSUE TITLE
The plugin does not support Chinese characters in .log() and .description()

### ISSUE THREAD

**Issue by wsj0415** [camel-tooling/camel-idea-plugin#964]
The plugin does not support Chinese characters, and if Chinese characters emerge in .log() and .description(), it will cause breakpoints to invalidation. Unable to enter breakpoint.

![image](https://github.com/camel-tooling/camel-idea-plugin/assets/151523045/d08ba978-29e9-441e-8145-06f9c5186100)

IntelliJ IDEA: 2023.2
Plugin version: 1.2.0
Apache camel: 3.20.3

**Comment by davsclaus** [comment]
Are you able to put a sample project code somewhere we can download and try to reproduce this

**Comment by wsj0415** [comment]
[camel-debug-demo.zip](https://github.com/camel-tooling/camel-idea-plugin/files/14447262/camel-debug-demo.zip)

**Comment by davsclaus** [comment]
I cannot reproduce this
<img width="1101" alt="Screenshot 2024-03-03 at 14 26 05" src="https://github.com/camel-tooling/camel-idea-plugin/assets/477100/8d523fe8-96a1-4e57-a16b-f84107487246">

**Comment by davsclaus** [comment]
I am using plugin 1.2.4 and IDEA 2023.3.4

**Comment by davsclaus** [comment]
cannot reproduce
