### ISSUE TITLE
Complains about simple expression in jsonPath despite allowSimple

### ISSUE THREAD

**Issue by dschulten** [camel-tooling/camel-idea-plugin#969]
In my route I have the following:

```
<transform>
    <jsonpath allowSimple="true">${header.KonfigJsonPath}</jsonpath>
</transform>
```

The plugin produces the error message: Illegal character at position 1 expected '.' or '[', although the allowSimple attribute should allow the simple expression.

**Comment by davsclaus** [comment]
Ah yeah that is a little tricky to do but we would likely need to enhance something in camel-catalog on the camel side for that to be able to have allowSimple = true|false

**Comment by davsclaus** [comment]
Okay so this is not possible as the synax validator would not understand that the simple should be evaluated to its actual value that json path is then used for validatoion.

**Comment by davsclaus** [comment]
This helps a bit, but I am afraid your jsonpath cannot be syntax checked in a way where we can't have the simple inlined.

One step on the way however is this
https://issues.apache.org/jira/browse/CAMEL-20197
