### ISSUE TITLE
Ensure that the Debugger still works with Camel 4.3

### ISSUE THREAD

**Issue by essobedo** [camel-tooling/camel-idea-plugin#977]
Lately, some important changes have been made in Camel which could affect the Debugger, this task aims to make the required modifications to make the Debugger compatible with Camel 4.3 if needed

**Comment by essobedo** [comment]
Related to https://github.com/camel-tooling/camel-idea-plugin/issues/963

**Comment by davsclaus** [comment]
works with 4.4
