### ISSUE TITLE
Camel route debugger

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#98]
This is maybe a bit more hardcore to implement. But would be nice if we can add breakpoints in the route dsl, and then have IDEA step through the route in debug mode.

**Comment by javaduke** [comment]
We use Camel almost exclusively to develop projects for our customers and an ability to debug Camel routes in XML DSL is very important for us. Perhaps we can work together to develop the debugger functionality? We can do most of the heavy lifting but I guess we need some help understanding how to connect all the dots. I do have some experience developing IDEA plugins but I'm not sure how do I debug a running Camel app (we use SpringBoot and Maven run configuration to run our apps from the IDE)

**Comment by davsclaus** [comment]
There is a Camel debugger API (BacklogDebugger) that can be "controlled" via JMX - eg add camel-management JAR as dependency, to have JMX enabled in Camel.
https://camel.apache.org/manual/backlog-debugger.html

Other tools such as hawitio uses this for their Camel debugger.

And tools like karavan will also work on a Camel visual debugger in the near future.

**Comment by davsclaus** [comment]
The hawtio uses the BacklogDebugger via Jolokia that can do JMX over REST.

You can see how the hawtio controller code here
https://github.com/hawtio/hawtio-integration/tree/master/plugins/camel/ts/debug

**Comment by javaduke** [comment]
I actually made some progress, mostly in the IntelliJ part of the implementation, but there are several things I haven't solved yet. First, if the camel processor or endpoint ID is not explicitly set up in the code, it is auto-generated by Camel, but then how can I find out its ID? Second, I'm not sure how can I receive notifications from the debugger that the breakpoint position is reached? There seems to be no way to add any listener to the MBean - or is there?
Perhaps we can sync up offline and discuss this? Is there any email address I can use to reach out to you?

**Comment by davsclaus** [comment]
You can reach out to us on the zulip chat
https://camel.zulipchat.com/

There is a camel tooling room where you can talk

**Comment by javaduke** [comment]
https://github.com/camel-tooling/camel-idea-plugin/pull/637
