### ISSUE TITLE
Formatter doesn't seem to work when a spicefic formatter like google-java-format is used

### ISSUE THREAD

**Issue by pai911** [camel-tooling/camel-idea-plugin#990]
First of all, thank you for the great work on this plugin! It helps Camel developers' life much easier!

However, I would like to report an issue, and see if there is a solution for it.

In my IntelliJ, the route DSL is formatted like the following with the built-in formatter.

<img width="757" alt="image" src="https://github.com/camel-tooling/camel-idea-plugin/assets/6234559/f244c453-e8a1-492b-81d4-1b253a7818a4">

But after enabling ` google-java-format ` plugin,
<img width="758" alt="image" src="https://github.com/camel-tooling/camel-idea-plugin/assets/6234559/e78e67a6-b1a1-4bd6-a08f-20c6f396dca0">

The result becomes like the following.
<img width="670" alt="image" src="https://github.com/camel-tooling/camel-idea-plugin/assets/6234559/cca96146-1830-4461-88b8-1d36c65f90e2">

Since it's a common use case to apply a 3rd party formatter across a company or team to reach a unified formatting style.
I'm wondering if it's possible to make the Camel formatter work with 3rd party formatter plugin?

**Comment by davsclaus** [comment]
Sorry I dont think so - or at least we often dont have time for such work. But we love contributions, so you are welcome to dive into the codebase and see if you can add support for this kind.

**Comment by pai911** [comment]
Do you mean you don't think it's quite common for a company or team to use a common formatter like `google-java-format`? 

If that is the case, then maybe it's not worth people to make a contribution?

**Comment by davsclaus** [comment]
> Do you mean you don't think it's quite common for a company or team to use a common formatter like `google-java-format`?
> 
> If that is the case, then maybe it's not worth people to make a contribution?

No we accept contributions, so its best if you or your company can denote time and engineers to work on this and build this feature and make sure it works, and send as PR to this project, thanks.

**Comment by davsclaus** [comment]
Maybe @essobedo have a few ideas about this as he helped implement the formatter in the plugin

**Comment by essobedo** [comment]
Unfortunately, I don't have any idea about this. AFAIU, you can only have one `FormattingService` called so if you enable the Google one, the core one (`CoreFormattingService`) won't be called consequently the `CamelPostFormatProcessor` won't be called either which means that at the end you will have your routes formatted with the Google style.

**Comment by pai911** [comment]
thank you guys for the info. I'll look into this if have time.
