### ISSUE TITLE
Breakpoint disabled: Camel EIP ID Not Found

### ISSUE THREAD

**Issue by jhoeflaken** [camel-tooling/camel-idea-plugin#999]
Hi,

I cannot get the debugging to work. As soon as the application starts my breakpoint is disabled with _Camel EIP ID not found_. Attached my simple application. I use _Camel Spring Boot Application_ configuration. I see the `.camel.debugger.pom.xml` being created and I get the popup that the Camel debugger was successfully connected.

Camel plugin version: 1.2.5
Spring Boot 3.2.3, Camel 4.4.0, IntelliJ 2023.3.5, Java 21 on WSL2.
Same on Windows with Spring Boot 3.2.3/Camel 4.4.0/Java 21 and Spring Boot 3.2.2/Camel 4.3.0/Java 21

![image](https://github.com/camel-tooling/camel-idea-plugin/assets/4974361/97f0de76-fd09-4458-b362-31102d0859f8)
[debug-test.zip](https://github.com/camel-tooling/camel-idea-plugin/files/14628684/debug-test.zip)

**Comment by jhoeflaken** [comment]
Is there any way I can debug the debugger plugin?

**Comment by essobedo** [comment]
Yes, you can launch in debug mode the `runIde` task, for more details refer to https://github.com/camel-tooling/camel-idea-plugin?tab=readme-ov-file#running-and-debugging-the-plugin-from-source

**Comment by jhoeflaken** [comment]
@essobedo Thnx. 

I will take a look.

Kind regards.

Jacob.

**Comment by jhoeflaken** [comment]
Hi,

I have found that the problem is within CamelDebugerSession#getBreakpointId.

The identified source locations are:

![image](https://github.com/camel-tooling/camel-idea-plugin/assets/4974361/fabc8d06-afa3-4b8f-9e08-65192d4d1490)

And therefore the XPath to locate the proper line in the route:

![image](https://github.com/camel-tooling/camel-idea-plugin/assets/4974361/c79f5062-20e2-40f3-80e7-7a1872053589)

But the routes document against the XPath is evaluated doesn't contain those attributes:

![image](https://github.com/camel-tooling/camel-idea-plugin/assets/4974361/5c06209b-e47e-411b-9b52-f9cba74b0fe9)

Do I need to set a specific setting to add these sourceLocation to a route?

Kind regards,

Jacob

**Comment by jhoeflaken** [comment]
@essobedo 

Seems to work now. Needed to add the following in application.yaml:

```
camel:
  springboot:
    main-run-controller: true
    source-location-enabled: true

spring:
  jmx:
    enabled: true
```
The source-location-enabled is false by default.

**Comment by essobedo** [comment]
The goal of `.camel.debugger.pom.xml` is to configure everything for you. So I will try to have a look asap, thx for the investigation and issue

**Comment by davsclaus** [comment]
Thanks for finding the problem. @essobedo see if you can find out if camel-debug JAR does not automatic enable this in both camel-main / camel-spring-boot and camel-quarkus

**Comment by turing85** [comment]
@essobedo if you need a reproducer for camel-quarkus: I updated the reproducer from https://github.com/camel-tooling/camel-idea-plugin/issues/930 to quarkus `3.9.1`; it shows the same behaviour.

**Comment by turing85** [comment]
Any progress on this?

**Comment by essobedo** [comment]
I started to investigate but unfortunately I could not find an easy fix for it and could not find enough time to investigate more. I will try to investigate more this week or next week

**Comment by davsclaus** [comment]
Did you find time to investigate more - In IDEA 2024.1.1 it seems that setting a breakpoint, cannot set it as a Camel breakpoint (only regular).

**Comment by davsclaus** [comment]
This will help for XML routes (as they do not have source loc:line)
https://issues.apache.org/jira/browse/CAMEL-20757

**Comment by davsclaus** [comment]
And this
https://issues.apache.org/jira/browse/CAMEL-20758

**Comment by essobedo** [comment]
@davsclaus did you plan to backport those changes into Camel 4.4?

**Comment by davsclaus** [comment]
Only if we get this to work first with main branch (ie 4.7.0) then we can look at what changes was done and what can be backported. 

However the debugger is wonky and does not seem to work so well in IDEA. Not sure if you or anyone else have time to look into this.

I am afraid that this IDEA plugin is community only

**Comment by davsclaus** [comment]
okay so it seems that the debugger rely on message history being enabled to have some details

**Comment by davsclaus** [comment]
https://issues.apache.org/jira/browse/CAMEL-20761

**Comment by davsclaus** [comment]
Okay I can get the example to debug OOTB with some more changes

<img width="1158" alt="Screenshot 2024-05-13 at 13 02 59" src="https://github.com/camel-tooling/camel-idea-plugin/assets/477100/131d5e20-4cf3-4420-a8d2-4971fe76aaa1">

**Comment by davsclaus** [comment]
This requires too many code changes and will not make it back to 4.4.x.

**Comment by davsclaus** [comment]
So this requires Camel 4.7 onwards to work OOTB. For older releases you can manually enable message history.
